#!/usr/bin/env python3
"""
=============================================================================
Universal DPO Shard Merger & Train/Val Splitter
=============================================================================
Combines sharded DPO pair JSONL files (*_shard_*.jsonl) generated by SLURM
Job Arrays into a single unified dataset, deduplicates by prompt/as_text,
and creates clean train and validation splits.
=============================================================================
"""

import argparse
import glob
import json
import logging
import os
import random
import sys
from typing import Dict, List, Set

logging.basicConfig(
    format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout)],
    level=logging.INFO,
)
logger = logging.getLogger("MergeDPOShards")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Merge DPO shard files into unified dataset.")
    parser.add_argument(
        "--input_pattern",
        type=str,
        required=True,
        help="Glob pattern matching shard JSONL files (e.g. 'data/corpus/dpo_pairs_mixup_shard_*.jsonl').",
    )
    parser.add_argument(
        "--output_file",
        type=str,
        required=True,
        help="Target unified JSONL file (e.g. 'data/corpus/dpo_pairs_mixup.jsonl').",
    )
    parser.add_argument(
        "--val_split_ratio",
        type=float,
        default=0.15,
        help="Validation split ratio (default: 0.15). If 0.0, no split is created.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for splitting and shuffling (default: 42).",
    )
    parser.add_argument(
        "--cleanup_shards",
        action="store_true",
        default=False,
        help="Delete shard files and their checkpoints upon successful merge.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    logger.info(f"Looking for shard files matching: {args.input_pattern}")

    files = sorted(glob.glob(args.input_pattern))
    if not files:
        logger.error(f"No shard files found matching pattern: {args.input_pattern}")
        sys.exit(1)

    logger.info(f"Found {len(files)} shard file(s): {files}")

    all_pairs: List[Dict] = []
    seen_keys: Set[str] = set()
    total_raw_lines = 0

    for fp in files:
        file_count = 0
        with open(fp, "r", encoding="utf-8") as f:
            for line_idx, line in enumerate(f, start=1):
                line = line.strip()
                if not line:
                    continue
                total_raw_lines += 1
                try:
                    record = json.loads(line)
                    if "type" in record:
                        if record["type"] == "pair":
                            pair_data = record["data"]
                        else:
                            continue
                    else:
                        pair_data = record

                    prompt_key = pair_data.get("as_text") or pair_data.get("prompt")
                    if prompt_key and prompt_key in seen_keys:
                        continue
                    if prompt_key:
                        seen_keys.add(prompt_key)

                    all_pairs.append(pair_data)
                    file_count += 1
                except Exception as e:
                    logger.warning(f"Skipping malformed line {line_idx} in {fp}: {e}")
        logger.info(f"  -> Loaded {file_count} unique valid pairs from {os.path.basename(fp)}")

    logger.info(f"Total raw records read: {total_raw_lines} | Unique valid pairs collected: {len(all_pairs)}")

    if len(all_pairs) == 0:
        logger.error("No valid pairs collected across all shards! Exiting with error.")
        sys.exit(1)

    random.seed(args.seed)
    random.shuffle(all_pairs)

    os.makedirs(os.path.dirname(os.path.abspath(args.output_file)), exist_ok=True)

    if args.val_split_ratio > 0 and len(all_pairs) > 10:
        split_idx = int((1.0 - args.val_split_ratio) * len(all_pairs))
        train_pairs = all_pairs[:split_idx]
        val_pairs = all_pairs[split_idx:]

        base, ext = os.path.splitext(args.output_file)
        eval_file = f"{base}_eval{ext}"

        with open(args.output_file, "w", encoding="utf-8") as f:
            for p in train_pairs:
                f.write(json.dumps(p, ensure_ascii=False) + "\n")
        logger.info(f"Wrote {len(train_pairs)} training pairs -> {args.output_file}")

        with open(eval_file, "w", encoding="utf-8") as f:
            for p in val_pairs:
                f.write(json.dumps(p, ensure_ascii=False) + "\n")
        logger.info(f"Wrote {len(val_pairs)} validation pairs -> {eval_file}")
    else:
        with open(args.output_file, "w", encoding="utf-8") as f:
            for p in all_pairs:
                f.write(json.dumps(p, ensure_ascii=False) + "\n")
        logger.info(f"Wrote all {len(all_pairs)} pairs -> {args.output_file}")

    # Optional cleanup of shard files and shard checkpoint files
    if args.cleanup_shards:
        logger.info("Cleaning up shard files and checkpoints...")
        for fp in files:
            try:
                os.remove(fp)
                logger.info(f"  Removed shard file: {fp}")
            except Exception as e:
                logger.warning(f"  Could not remove {fp}: {e}")

            ckpt_fp = f"{fp}.checkpoint.jsonl"
            if os.path.exists(ckpt_fp):
                try:
                    os.remove(ckpt_fp)
                    logger.info(f"  Removed checkpoint file: {ckpt_fp}")
                except Exception as e:
                    logger.warning(f"  Could not remove {ckpt_fp}: {e}")

    logger.info("=== DPO Shards Merge Completed Successfully ===")


if __name__ == "__main__":
    main()
